### ISSUE TITLE
Use WebKit on Windows?

### ISSUE THREAD

**Issue by adamv** [etexteditor/e#4]
The Linux build is moving to embed WebKit as the browser used for preview and external script output. Potentially we could move to WebKit on Windows too instead of embedding IE, but I don't really have a preference.

**Comment by ThePixelDeveloper** [comment]
I think it's a good idea. Web kit is more standards compliant and will provide an all round better experience.

**Comment by astigsen** [comment]
We might move towards offering both on windows. But WebKit is quite large, and ie is essentially free (size wise) on windows. So there have to be some serious benefits.

**Comment by adamv** [comment]
File size considerations mean embedding IE is preferable on Windows for now. (If Google Chrome provided an ActiveX things might be different.) Closing.

**Comment by ghost** [comment]
Seeing as E is supposed to be compatible with TextMate bundles, and TextMate runs on Mac... which runs WebKit. Forgive me if I'm wrong in presuming TextMate uses WebKit, but if it does using the same rendering engine in E would presumably offer more compatibility.

**Comment by tea** [comment]
I'm not really happy with WebKit dependency in E. Back then when it was bundled it was the only usable wxWidgets-aware choice; however it was and it is huge, has many dependencies to match and wxWidgets port seems to be second-class citizen among webkit ports. E already embeds wxwebconnect (which uses external Gecko aka firefox engine) but integration seems to be unfinished so maybe one day when I have some time I'll try to use webconnect instead of webkit.

2 oheard: TM probably uses WebKit but any html engine should be conforming to W3C standards and thus should be freely interchangeable without hurting compatibility. IIRC TM bundles don't use any of webkit-only features so any conforming engine should do.
