### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by danpal** [etexteditor/e#54]
1.  Windows build instructions are gone.
2. On  get_externals_win.sh 
   curl -O http://kent.dl.sourceforge.net/sourceforge/tinyxml/tinyxml_2_5_3.tar.gz
   Fails, it retrieves a HTML document instead.
3. After I finish building dependencies, building the projects gives an error errors:

Error   2   error LNK2001: unresolved external symbol _ltm_desc ecored.lib  e-exe

**Comment by adamv** [comment]
SourceForge changed their URLs (again) since this setup script was created; feel free to branch, change the URL to:
http://downloads.sourceforge.net/project/tinyxml/tinyxml/2.5.3/tinyxml_2_5_3.tar.gz
and push.

**Comment by danpal** [comment]
OK I will fix those...but I still can't build, the link error is still there:
Error 2 error LNK2001: unresolved external symbol _ltm_desc ecored.lib e-exe

**Comment by adamv** [comment]
Dan, my master branch has been updated to build and link from a clean get: http://github.com/adamv/e/commit/c169f18e720254436eb72d31a7db14c04b290407

**Comment by astigsen** [comment]
closing

**Comment by jeremywiebe** [comment]
I pulled the e source code today and tried to build on Windows.  crypt was not available at the url specified (host is down) and same with ltm.  I Googled around and couldn't find the crypt lib anywhere to download so at this point I can't build e.  I wonder if it'd make for a more reliable build if the currently required versions of these libraries were hosted as downloads here on the GitHub project instead of depending on the various projects download sites.  It appears that specific versions are required anyways so going to the project download site isn't a benefit (as might be the case if you always wanted the latest version).
